public with sharing class Constants {
    
    //Trigger Events
    public static final String BEFORE_INSERT = 'isBeforeInsert';
    public static final String AFTER_INSERT = 'isAfterInsert';
    public static final String BEFORE_UPDATE = 'isBeforeUpdate';
    public static final String AFTER_UPDATE = 'isAfterUpdate';
    public static final String BEFORE_DELETE = 'isBeforeDelete';
    public static final String AFTER_DELETE = 'isAfterDelete';
    public static final String AFTER_UNDELETE = 'isAfterUndelete';
    
    
    //Object API Name
    public static final String OBJ_API_USER                 = 'User';
    public static final String OBJ_API_PORTALUSER           = 'PortalUser';
    public static final String OBJ_API_ACCOUNT              = 'Account';
    public static final String OBJ_API_CASE                 = 'Case';
    public static final String OBJ_API_CSBYPASS             = 'CS_Bypass__c';
    public static final String OBJ_API_EMAILMESSAGE         = 'EmailMessage';
    public static final String OBJ_API_POLICY               = 'Policy__c';
}